export const FETCH_GIFT = 'FETCH_GIFT';
export const ADD_TO_INVENTORY = 'ADD_TO_INVENTORY';
export const REMOVE_FROM_INVENTORY = 'REMOVE_FROM_INVENTORY';
export const ADD_CHARACTER = 'ADD_CHARACTER';
export const EMPTY_INVENTORY = 'EMPTY_INVENTORY';